-- Create table en oracle con auto-increment
CREATE TABLE USUARIO
(
    ID INT GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    NOMBRE VARCHAR(50) not null,
    EDAD INTEGER not null,
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);
